apiVersion: v1
kind: Service
metadata:
  name: scrolller-web-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 80
      targetPort: 80
  selector:
    app: scrolller-web